node-opcua/node-opcua

lib/client/node_crawler.js
This is for convenience to be able to later access the referenced nodes.
=> Added nodeId to object returned from NodeCrawler.read.

lib/client/client_subscription.js
This simple commit tries to resolve/coerce a NodeId early when initiating a monitor.
Before, the coercion happens within a setImmediate, which mean that errors can't be caught in try/catch and the stack trace goes missing.
I got a bit lost tracing the details, but the result of resolution could be cached to eliminate some reworking?
=> Resolve nodeIds early when monitoring to propagate errors faster.

lib/datamodel/access_level.js, lib/datamodel/nodeid.js, lib/datamodel/numeric_range.js, lib/misc/encode_decode.js, lib/misc/enum.js, lib/misc/factories_enumerations.js, lib/misc/factory_code_generator.js, lib/misc/packet_analyzer.js, lib/misc/security_policy.js, lib/server/subscription.js, lib/services/browse_service.js, package.json, test/misc/test_enum.js
Hi.
I want to use node-opcua to operate with some plc devices in low power computer. The functionality is well, but performance does not come up to expectation. So I fired up profiling and discovered that new Variant and Enum.get use too much cpu. These commits are based on the profiling.
The performance test I did is monitoring 1000 double variables with sampling interval 100ms and publishing interval 100ms. The original node-opcua ate up all cpu ( AMD E-450 1.6G Hz), but can not catch up the publishing interval ( got 90 publishing in 30s). After these fixes, the cpu usage is about 60% after JIT warm up, and no publishing is missing. It's about 4-5 times performance enhancement in pure monitoring application.
Hope these changes could be merged. All tests are passed on node v0.12.2.
=> some performance tuning

lib/client/node_crawler.js
Hi Etienne,
This PR adds `NodeClass` to the resultmask. We saw a need for this information to be returned to be able to fully separate different node types in our program. We add the nodeclass to the `obj`-object that is passed to the callback.
It might be an idea to have the user specify what is needed in the resultmask, and pass it to the function as an argument. If you think that this is a better way, then we could refactor it to do this. 
Regards,
@perok and @hanskhe
=> Implement NodeClass for NodeCrawler

lib/address_space/address_space.js, test/address_space/test_issue_104.js
When node IDs are automatically generated, node IDs that are already in use will be skipped.
=> Fix issue #104

README.md
- After cloning the repository, user should execute `npm install` instead of `npm init` in order to have the client or the server run properly. `npm install` takes care of installing all the project dependencies.
- Fix broken link to the server tutorial.
- Remove directory name parameter from the last `git clone` example to make it consistent with the rest of the README file.
- Create a issue -> Create **an** issue
=> Basic README fixes

lib/address_space/ua_variable.js
Bind to variable if timestamped_set used to determine context
=> If used timestamped_set, no context is set

lib/transport/client_tcp_transport.js, test/end_to_end/test_e2e_connection_reconnection.js
I discovered an non deterministic behavior using this module as a client & server in my middleware.
The following test case brought up this behavior:
1. init client (--> client.pending)
2. client connected (--> client.connected)
3. stop server (--> client.start_reconnection)
4. start server (--> client.connection_reestablished)
When the server is stopped the client connection terminates in most cases with socket error ECONNRESET which causes connection_break event. This event initiates the reconnection process.
However, in some cases the client connection terminates with socket error EPIPE which led to a timeout.
EPIPE  The local end has been shut down on a connection oriented socket.  In this case, the process will also receive a SIGPIPE unless MSG_NOSIGNAL is set.
From my point of view …
=> Error Handling for Socket Error EPIPE added

lib/address_space/load_nodeset2.js, test/address_space/test_load_nodeset2.js, test/fixtures/fixture_node_with_predefined_string_variable.xml
When modelling the address space, I defined some variables for server side configuration routines. Unfortunately, the value was not part of the runtime space. I extended the loading routine parser to recognize string values from xml models.
=> Read predefined string values for variables from nodeset xml

index.js
There's an undocumented function for creating a discovery server. There's even a test so I figured maybe the missing module in index.js was not intentional.
=> Add OPCUADiscoveryServer to index.js

lib/client/opcua_client.js
The documentation suggests that the `closeSession` method would take only 2 parameters: `session` and `callback`. Nevertheless, when reviewing the source code reality is different. It takes 3 params. A brief description of this missing parameter (`deleteSubscriptions` - Boolean) is proposed with this commit.
=> Update opcua_client.js to document closeSession param

lib/client/opcua_client.js
Enhances opcua_client.js - createUserNameIdentityToken method
+ allows username/password authentication with servers without certificate
+ allows username/password authentication with servers not providing serverNonce - resolves #196
=> opcua_client.js - createUserNameIdentityToken

lib/address_space/load_nodeset2.js, test/address_space/test_load_nodeset2.js, test/fixtures/fixture_node_with_predefined_variable.xml
When modelling the address space, I defined some variables for server side configuration routines. Unfortunately, the value was not part of the runtime space. I extended the loading routine parser to recognize boolean values from xml models.
=> Read predefined boolean values for variables from nodeset xml

lib/client/node_crawler.js
It was observed repeatedly on an OPC server in production. This permits the crawler to continue. I haven't got any clue on how this can actually happen but it did :-)
If it is not ok just to return null, then what should the error strategy then be in the crawler?
=> fix, for some reason status was good however dataValue.value was null

lib/address_space/base_node.js, lib/address_space/ua_object.js, lib/address_space/ua_object_type.js, lib/address_space/ua_variable.js, lib/address_space/ua_variable_type.js
Problem: for using custom Nodesets with opcua.OPCUAServer to load a .xml models it is not possible to manage the behavior for modellingRule="OptionalPlaceholder" when creating a inctance of the model.
Solution: add Callback that is triggered on create new node:
e.g.
server = new opcua.OPCUAServer({
port: 26543, // the port of the listening socket of the server
resourcePath: "UA/"+ serverName, // this path will be added to the endpoint resource name
nodeset_filename: additionalNodeset
});
function onAddNode(parent, node, instance) {
console.log(" new Object: " + node.browseName + " : " + node.modellingRule);
if (node.modellingRule.indexOf("Placeholder") >= 0) {
/// Add "NewObject" Methode for every modellingRule=="OptionalPlaceholder"
addMethodNew(parent, node);    
}
} …
=> Add Callback for every object created by instantiate

lib/server/opcua_discovery_server.js, test/discovery/test_discovery_server.js
I was trying out OPCUADiscoveryServer and I noticed that the response did not include `applicationUri` which is crucial to identify a specific server from the list.
In the source code comment:
```
// The globally unique identifier for the application instance. This URI is used as
// ServerUri in Services if the application is a Server.
```
So, I would assume applicationUri was intended to be used by applications to identify registered servers.
=> Fix missing applicationUri in findServers response

lib/address_space/historical_access/address_space_historical_data_node.js
Fix a null pointer exeption if sourceTimestamp is NULL on "value_changed" event in historical_data store
=> Fix historical_data store on sourceTimestamp==null

node-opcua.d.ts
Added minimal declarations for this to work. I didn't cover every parameter. In particular, filter extension objects are not covered.
I'm not completely happy that resolveNodeId and read_service are exposed in a slightly non-Typescript way, but this is a direct translation of the Javascript and is the way node-opcua is structured AFAICT.
Example code:
```
import {DataType, Variant, ClientSession, AttributeIds, OPCUAClient, ClientSubscription, resolveNodeId, read_service} from "node-opcua";
const client = new OPCUAClient({});
client.connect("http:://SERVER:PORT", function (_err) {
client.createSession(function (err, session: ClientSession) {
const subscription = new ClientSubscription(session, {
requestedPublishingInterval: 100,
requestedLifetimeCount: 10,
requestedMaxKeepAliveCount: 2, …
```
=> Add necessary Typescript declarations for monitoring values

packages/node-opcua-service-call/schemas/CallMethodResult_schema.js
I ran into a crash where `CallMethodResult_Schema` was undefined. I believe this is just missing a `var` keyword, and after modifying this file, it seems to solve the issue.
=> Add missing var keyword for CallMethodResult_Schema

packages/node-opcua-variant/src/variant_tools.js, packages/node-opcua-variant/test/test_variant_sameVariant_pull_request.js
Int64 and Uint64 values are saved as Arrays and can't can't be compared with v1.value === v2. value
ByteString is a Buffer and can't compared so either.
=> sameVariant function didn't work with Int64, Uint64 & ByteString

packages/node-opcua-address-space/src/ua_variable.js, packages/node-opcua-address-space/test/test_accessLevel_userAccessLevel_pullrequest.js
userAccessLevel can't be higher than accessLevel of variables but by creating the variables the server doesn't compare this accessLevels so in node-opcua it can be higher:
Spec Part 3 R 1.04 page 27
=> userAccessLevel is not matched with variable accessLevel

packages/node-opcua/package.json
a3a3d2d4d51b18e95ba427d572b8cffc2c0b55dc required ` semver`  and `colors`.
While `colors` gets pulled in by the sub-packages, ` semver` gets not (anymore?).
=> Add missing dependencies to node-opcua

packages/node-opcua-secure-channel/src/security_policy.js
Fixed wrong Uri for _Basic256Sha256_ `asymmetricSignatureAlgorithm`
See **OPCFoundation** UA-.NETStandard [SecurityConstants](https://github.com/OPCFoundation/UA-.NETStandard/blob/7c0fe4f44af0ead9679995e4e87b634499e08e9b/Stack/Opc.Ua.Core/Security/Constants/SecurityConstants.cs) _(line 38)_
=> Fixed wrong asymmetricSignatureAlgorithm

packages/node-opcua-server/src/validate_filter.js, packages/node-opcua-server/test/test_subscription_with_monitored_items_boolean_string_bytestring.js
Server returns BadFilterNotAllowed if the DataChange Trigger is changed on a non numeric Monitored Item with DeadbandType = None.
It should only return BadFilterNotAllowed when the DeadbandType != None
=> fixed BadFilterNotAllowed on boolean, String, ByteString & LocalizedText

packages/node-opcua/node-opcua.d.ts
For my typescript client application I needed the call method and also found some problems with usage of the StatusCode type (StatusCodes was used instead).
=> Method "call" added to ClientSession, StatusCode type usage fixed

packages/node-opcua/node-opcua.d.ts
The OPCUAClientBase expose the "on" method to subscribe on events, but "eventHandler" function does not declare any args. This is a problem (in Typescript)  when the client would like to subscribe on "backoff" event like:
this.client.on("backoff", (number, delay) => {
})
This is not possible because the eventHadler is declared such this:
eventHandler: () => void
=> Update node-opcua.d.ts  OPCUAClientBase event on

packages/node-opcua-client/src/client_base.js
It is not possible to create a new OPCuaClientBase() with an own certificate and private_key.
The parameter to deliver the path is missing.
```
const options = {
connectionStrategy: params.connectionStrategy,
endpoint_must_exist: false,
certificateFile: params.certificateFile,
privateKeyFile: params.privateKeyFile,
applicationName: params.applicationName
};
```
=> add parameter to load own certificate/key from specific path

packages/node-opcua-client/src/client_session.js, packages/node-opcua-end2end-test/test/end_to_end/u_test_e2e_browse_read.js
**I'm submitting a ...**  (check one with "x")
- ( ) bug report => search github for a similar issue or PR before submitting
- ( ) feature request
- ( ) support request => Please do not submit support request here, instead see use 
- use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
- [contact Sterfive for commercial support](https://www.sterfive.com)
- (x) new feature
**Current behavior**
The node-opcua does not return the contain references in the item 'DataBlocksGlobal'
**Expected behavior**
The node-opcua could browse forward references and the S7-1500 Object 'DataBlocksGlobal'.
**Minimal reproduction of the problem with instructions**
1. create a client instance
2. create a none …
=> change Service parameter to browse Objects forward (siemens S7-1500)

documentation/creating_a_server.md, documentation/creating_a_server_with_a_historizing_variable.md, documentation/sample_server.js, documentation/sample_server_with_historizing_variable.js, packages/node-opcua-samples/bin/demo_server_with_alarm.js
I replace all occurance of `resourcePath: "UA/MyLittleServer"` into `resourcePath: "/UA/MyLittleServer"`.
I am new to opcua, when I follow the document to create a server instance, I would get 
```
$ node ./demo_server_with_alarm.js
/Users/agu/workshop/opcua-server-demo/node_modules/node-opcua-assert/dist/index.js:19
throw err;
^
Error: Certificate file must exist :/Users/agu/workshop/certificates/server_selfsigned_cert_2048.pem
at Object.assert (/Users/agu/workshop/opcua-server-demo/node_modules/node-opcua-assert/dist/index.js:10:21)
at OPCUAServer.getCertificateChain (/Users/agu/workshop/opcua-server-demo/node_modules/node-opcua-common/dist/opcua_secure_object.js:45:33)
at createEndpoint (/Users/agu/workshop/opcua-server-demo/node_modules/node-opcua-server/dist/opcua_server.js:463:44) …
```
=> resourcePath should start with / if defined

packages/node-opcua-client-proxy/source/proxy_manager.ts
After upgrading to 2.1.5 in my project, `tsc` started complaining about code in `node_modules/node-opcua-client/source/private`, and I got similar errors when trying to build `node-opcua`. 
This seems to fix it, hope it's useful.
=> Use ClientSession instead of ClientSessionImpl in node-opcue-client-proxy

packages/node-opcua-server/source/opcua_server.ts, packages/node-opcua-server/test/test_server_with_multiple_hostname.ts
Related to issue #647, this is a fairly lightweight change to expose the hostname option when creating the default endpoints.
=> Expose endpoint hostname option in server options

packages/node-opcua-nodeid/package.json
See title.
For me it created some issues while using npm pack for offline installation.
=> Added missing 'chalk' dependency for node-opcua-nodeid

packages/node-opcua-end2end-test/test/end_to_end/test_umbrella_e2e.js, packages/node-opcua-end2end-test/test/end_to_end/u_test_e2e_createsSession_endpoints.js, packages/node-opcua-server/source/opcua_server.ts
- serverEndpoints need to be populated with valid server endpoints even if
the client did not connect with exactly the same endpoint as one exposed
by the server.
- prior to this fix, node-opcua server was returning serverEndpoints=null
when the endppoint used by the client was unknown. This causes
third party client to reject the connection as they couldn't verify
the endpoints.
- https://reference.opcfoundation.org/v104/Core/docs/Part4/5.6.2/
- the spec says:
The Server returns its EndpointDescriptions in the response. Clients
use this information to determine whether the list of EndpointDescriptions
returned from the DiscoveryEndpoint matches the Endpoints that the
Server has. If there is a difference then the Client shall close
the Session and report an error. The Server returns all …
=> fix serverEndpoint in CreateSessionResponse

packages/node-opcua-server/source/opcua_server.ts
filter out restricted endpoints from the create session response. In the _on_CreateSessionRequest, the endpoint to use in the session needs to  be an non-restricted endpoint. Some OPC clients e.g. UA Expert then try to connect using an UserIdentityToken that is not present for the endpoint and cannot be found in the function:
findUserTokenByPolicy of opc_server.ts
=> avoid exposure of restricted endpoints in createsessionresponse message

packages/node-opcua-client/source/client_monitored_item_group.ts, packages/node-opcua-client/source/private/client_monitored_item_group_impl.ts, packages/node-opcua-client/test/test_monitoreditemtoolbox.ts
if the createMonitoredItems call inside the  MonitoredItemToolbox returns an error ( e.g. BadTooManyOperations) from the server, this error cannot be handled specifically at the moment because the terminated event is thrown without any error information so the user cannot handle the situation specifically.
=> emit Error object if MonitoredItemGroup fails on creation 

documentation/client_typescript.js, documentation/client_typescript.ts, documentation/creating_a_client_callback.md, documentation/creating_a_client_typescript.md, documentation/mini_crawler.ts, documentation/sample_client.js, documentation/sample_client_ts.ts, documentation/test_client_reconnection.js
I am currently working my way into the software. Very good work by the way. 
in the examples from the documentation I get a warning message that endpoint_must_exist is depcricated.  So i renamed it in the documentation.
=> rename endpoint_must_exist to endpointMustExist in Documentation

packages/node-opcua-data-model/source/diagnostic_info.ts, packages/node-opcua-data-model/test/test_diagnostic_info.js, packages/node-opcua-server/source/opcua_server.ts, packages/node-opcua-server/test/test_server_diagnostic_filter.js
This PR corresponds to issue #1093. The diagnostic information is filtered out in the final response generation based on the bit values set in the `requestHeader` (`returnDiagnostics`). The translation is according to [this](https://reference.opcfoundation.org/v104/Core/docs/Part4/7.28/) specification.
=> fix for #1093. filter out unrequested diagnostic information.

packages/node-opcua-server/source/user_manager.ts
When initializing a OPCUAServer with a valid `userManager`
configuration (according to the provided interfaces), the server
crashes with a runtime exception caused by an illegal access error.
=> fix: illegal access error

packages/node-opcua-address-space/src/historical_access/address_space_historical_data_node.ts, packages/node-opcua-address-space/src/ua_variable_impl.ts, packages/node-opcua-certificate-manager/source/certificate_manager.ts, packages/node-opcua-client-crawler/source/node_crawler_base.ts, packages/node-opcua-server/source/opcua_server.ts, packages/node-opcua-server/source/server_engine.ts, packages/node-opcua-server/test/test_server_engine.js, packages/node-opcua-xml2json/source/xml2json.ts
When implementing tests using `jest` in projects that use this
library, tests fail for no apparent reason. This is because the
implementation of this library uses `promisify` of the node internal
`util` module to promisify some functions implemented using
callbacks. The callback functions created by `promisify` do not
fulfill the `instanceof Function` check when executed in a `jest`
environment which leads to unexpected errors during tests execution.
This issue is related to the following issue in the `jest` project
https://github.com/facebook/jest/issues/2549.
A simple workaround was to replace all `instanceof Function` checks
by a `typeof callback === 'function'` check.
The issue was described in the following comment:
https://github.com/facebook/jest/issues/2549#issuecomment-1104834577
=> fix: code behaves differently when executed in `jest` runtime

packages/node-opcua-client/source/tools/findservers.ts
A max retry should be used so that the connect attempt will throw an error if the discovery server cannot be reached. Without a max retry the callback is never executed, leaving any callers of these functions without any way to handle this type of scenario.
=> Add a max retry to findServers and findServersOnNetwork to prevent infinite retries

packages/node-opcua-convert-nodeset-to-javascript/package.json, packages/node-opcua-schemas/package.json, packages/node-opcua-server/package.json, packages/node-opcua-service-discovery/package.json
In multiple internal packages `chalk` is a missing dependency, causing the production build to fail: 
```
Error: Cannot find module 'chalk'
Require stack:
- /home/node/core/node_modules/node-opcua-service-discovery/dist/bonjour.js
- /home/node/core/node_modules/node-opcua-service-discovery/dist/index.js
- /home/node/core/node_modules/node-opcua/dist/index.js
- /home/node/core/index.js
```
I added missing dependency in the packages that use `chalk` but have no `chalk` dependency specified in `package.json`
=> fix: add missing chalk dependency

packages/node-opcua-transport/source/tcp_transport.ts, packages/node-opcua-transport/test/test_client_tcp_transport.js
Background: in `tcp_transport`, `prematureTerminate` calls Socket::destroy which asynchronously emits the `close` event, but that same function removes all the listeners before nodeJS can process this close event. As a result the `socket_closed` event is not emitted by TcpTransport and the open connections from base_server leak. This eventually causes the OPC-UA servers to refuse all connections as it thinks that it reached its max (DDOS protection)
I observed the bug as we have an LDS running and some OPC-UA servers (both from this library) registering to it. For some reason not fully clear to me, when the OPC-UA server has its internal clock in the future compared to the LDS, it does not properly close the socket. This causes the LDS tcp_transport to use its internal timeout to …
=> TCP transport does not close dependants in case of timeout

packages/node-opcua-server/source/opcua_server.ts, packages/node-opcua-server/source/server_end_point.ts, packages/node-opcua-server/test/test_server_issue_1303.ts
Closes #1303
Ensure that the OPCUAServer correctly binds to the provided hostname when creating the TCP server. 
Previously, it was defaulting to [unspecified IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address) (::) when IPv6 is available, or the [unspecified IPv4 address](https://en.wikipedia.org/wiki/0.0.0.0) (0.0.0.0) otherwise.
- Added new test cases to validate the hostname parameter behavior.
=> feat: bind hostname to tcp server when passed to OPCUAServer

packages/node-opcua-client-dynamic-extension-object/source/get_extra_data_type_manager.ts, packages/node-opcua-client-dynamic-extension-object/source/populate_data_type_manager.ts, packages/node-opcua-client-dynamic-extension-object/source/private/populate_data_type_manager_103.ts, packages/node-opcua-client-dynamic-extension-object/source/promote_opaque_structure.ts, packages/node-opcua-client/source/private/client_session_impl.ts, packages/node-opcua-client/source/private/opcua_client_impl.ts, packages/node-opcua-end2end-test/test/test_datatype_manager_regeneration.ts
- improve parallelisation of dataType definition extraction 
- add test to ensure caching is properly managed in particular check that cache get cleared when reconnection leads to a reconstructed client session and is preserved when session can be recycled.
=> improve getExtraDataTypeManager and caching

packages/node-opcua-server/source/server_subscription.ts, packages/node-opcua-server/test/test_subscription_with_monitored_items.ts
Prior to emitting the `removeMonitoredItem` event, the MonitoredItem instance is disposed. This resets all properties of that MonitoredItem. When the `removeMonitoredItem` event is raised, a subscriber cannot retrieve any information from this instance (i.e. the item which was monitored).
Therefore the MonitoredItem instance is disposed after emitting the event.
=> Dispose MonitoredItem after event

packages/node-opcua-address-space/src/base_node_impl.ts, packages/node-opcua-address-space/test/test_referencetype.ts, packages/node-opcua-address-space/test/test_remove_reference.ts
fix an issue in BaseNode.remove_reference that would not clear the added javascript properties on the parent Node when remove_reference is called on the child.
=> fix issue in BaseNode.remove_reference

packages/node-opcua-client/source/private/opcua_client_impl.ts
This PR addresses https://github.com/node-opcua/node-opcua/issues/1431
When using the dockerized asyncua opc server, the `serverCertificate` becomes the empty Buffer. This PR adds a fallback so that empty buffers and strings also use the unencrypted password.
=> fix: unencrypted password on empty buffer server certificate

packages/node-opcua-client/source/private/client_session_impl.ts
Hello, 
this PR is to fix the error reported in #1387 
I am not sure how to set a working test since it would require the complexity of mocking a server and create a session, but I tried to run all the tests that have already been defined, and they are successful.
=> fixes the parsing of the ClientSession.timestampsToReturn argument
