node-opcua/node-opcua

test/end_to_end/test_opcua_ClientServer_crawl_write_crawl.js

Hi,
We have started to write a test for our crawler problem. It's crudely based on your tests.
The problem is that the crawler does not call the success callback after a write operation (tested on node 'EnabledFlag' (n=0;i=2294)).
The idea is to test that the nodecrawler returns data after a write operation. Currently we are trying to write to 'EnabledFlag' (n=0;i=2294). We get the error ''The node id refers to a node that does not exist in the server address space." on the write operation. Could you guide us in the right direction?
Thanks

Initial crawl write crawl test

---

lib/client/client_session.js

minor documentation fix i assume form 4 is meant to be with an array

client browse documentation fix

---

documentation/creating_a_client.md

Update documentation of sample client

Update documentation of sample client

---

lib/address_space/base_node.js

There's an obstrusive message showing up every time a server starts so at least I would like the message to be correctly typed :) Helping a bit to solve #190

Update base_node.js to correct typo

---

README.md

[![Build Status](https://travis-ci.org/node-opcua/node-opcua.svg?branch=ES6)](https://travis-ci.org/node-opcua/node-opcua)

ES6 branch Build status

---

packages/node-opcua/node-opcua.d.ts

- `WriteValue` class
- `DiagnosticInfo` class
- `write` method for ClientSession
this exposes some part of the API to Typescript for better development

Adding some missing TS declarations

---

packages/node-opcua-address-space/src/referenceType.js

fix: Remove duplicate export

---

documentation/creating_a_client.md

* fix \<pre\> block under client instantiation
* add descriptive texts with some more information
* fix some typos
* make code-formatting more consistent

review and update client tutorial

---

packages/node-opcua-address-space/src/loader/load_nodeset2.js
packages/node-opcua-address-space/test/test_load_nodeset2.js
packages/node-opcua-test-fixtures/fixture_node_with_predefined_variable.xml

Add float and boolean parser options

---

packages/node-opcua/node-opcua.d.ts

This is a first pass over the TypeScript declaration files for issues we came across while working with the library:
- Added a definition for `class NodeId`
- changed inline comments so they are discoverable by Intellisense (see Screenshot from VS Code)

Improve TypeScript declaration

---

packages/node-opcua-end2end-test/test/end_to_end/test_e2e_frequent_server_restart.js

some more scenarios as it could happen inside Node-RED

test(server,client): update the frequent test

---

packages/node-opcua-client/src/client_base.js

I'm suspecting, that this log line has a typo.

Fix typo in endpoint

---

packages/node-opcua/node-opcua.d.ts

callback function parameter did not include (err, response)

Update writeSingleNode method signature

---

packages/node-opcua-client-crawler/src/node_crawler.js

Fix typo in the followReference function

Fix typo in the followReference function

---

packages/node-opcua-server/source/opcua_server.ts

Fixes missing type names in .d.ts generation in on events request and response

Add 2 missing type imports

---

packages/node-opcua-address-space/source/loader/load_nodeset2.ts
packages/node-opcua-address-space/test/test_load_nodeset2.ts
packages/node-opcua-address-space/test_helpers/test_fixtures/mini.nodeset.withVariousVariables.xml

The function for parsing ListOfString xml elements was missing from the nodeset loader. ListOfString elements were loaded as just a single string instead of a list.

Added ListOfString to the nodeset loader.

---

packages/node-opcua-client/source/client_base.ts
packages/node-opcua-client/source/client_session.ts
packages/node-opcua-data-model/source/localized_text.ts
packages/node-opcua-data-model/source/qualified_name.ts
packages/node-opcua-pseudo-session/source/basic_session_interface.ts
packages/node-opcua-variant/source/variant.ts

Simplify Client api by removing unecessary option in XXXLike Structures

Improve YYYLike structure for a better coding experience

---

packages/node-opcua-modeler/readme.md

I changed a few typos in the readme file

fixed modeler readme file

---

packages/node-opcua-client/source/private/client_base_impl.ts
packages/node-opcua-end2end-test/test/test_dos_attack_by_consuming_secure_channel_and_not_using_them.js
packages/node-opcua-end2end-test/test/test_dos_attack_by_repeating_connection_when_securechannel_failed.js
packages/node-opcua-factory/source/factories_baseobject.ts
packages/node-opcua-file-transfer/source/server/file_type_helpers.ts
packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts
packages/node-opcua-secure-channel/source/server/server_secure_channel_layer.ts
packages/node-opcua-server/source/base_server.ts
packages/node-opcua-server/source/i_channel_data.ts
packages/node-opcua-server/source/i_socket_data.ts
packages/node-opcua-server/source/opcua_server.ts
packages/node-opcua-server/source/server_end_point.ts
packages/node-opcua-transport/source/message_builder_base.ts
packages/node-opcua-transport/source/server_tcp_transport.ts

- fix a bug by which channel are not released when OpenSecureChannelRequest
failed on the server, causing inability for clients to connect
anymore after a while
- add OPCUAServer "connectionRefused"  event
- add OPCUAServer "openSecureChannelFailure" event

improve OpenSecureChannelRequest failure

---

packages/node-opcua-address-space/source/address_space_ts.ts
packages/node-opcua-address-space/src/namespace.ts
packages/node-opcua-address-space/src/ua_method.ts
packages/node-opcua-data-model/source/access_level.ts
packages/node-opcua-end2end-test/test/end_to_end/test_e2e_issue896_execute_method_access_control.ts

Actual state of the PR
the addad e2e works if I run it seperatly, but not if I run it with npm test.
Hekp welcome!

Executing UAMethod should check user authorization

---

packages/node-opcua-address-space/source/session_context.ts
packages/node-opcua-server/source/opcua_server.ts

doc: User with multiple roles

---

packages/node-opcua-address-space/source/helpers/argument_list.ts
packages/node-opcua-address-space/test/test_argument_list.ts

* input arguments not provided are returned as BadNoData
* Check for BadTypeMismatch even if the number of args does not match

improve method inputArgumentResult

---

packages/node-opcua-client/source/opcua_client.ts
packages/node-opcua-client/source/private/opcua_client_impl.ts
packages/node-opcua-client/test/test_opcua_client.js
packages/node-opcua-end2end-test/test/test_server_with_inconsistent_revisedSessionTimeout.ts

[CLIENT] fix handling of inconsistent revisedSessionTimeout sent by server

---

packages/node-opcua-nodeid/source/nodeid.ts
packages/node-opcua-nodeid/test/test_nodeid.js

https://reference.opcfoundation.org/v104/Core/docs/Part6/5.3.1/#Table20

switch encoding of Binary NodeId string rep from hex to base64

---

packages/node-opcua-debug/package.json

Install chalk as dependency instead of devDependency

---

packages/node-opcua-nodesets/nodesets/Opc.Ua.MachineTool.NodeSet2.xml

fix: Update MachineTool to `1.01.1`

---

packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts
packages/node-opcua-server/source/opcua_server.ts

Hi,
This is my first MR for this project :) 
Fix #1170

Fix producturi in session

---

packages/node-opcua-address-space/source/index.ts
packages/node-opcua-address-space/src/data_access/ua_multistate_value_discrete_impl.ts
packages/node-opcua-address-space/test/data_access/test_multi_state_value_discrete_type_from_nodeset.ts

I have extracted data type validation into separate function and added full test coverage

issue-1215-bugfix: UAMultiStateValueDiscrete value of UINT64 type results in exception

---

packages/node-opcua-client/source/private/client_base_impl.ts
packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1331.ts
packages/playground/reconnection_workbench.js

ensure client.isReconnecting=true when client emits the 'connection_reestablished' event 

---

packages/node-opcua-chunkmanager/source/chunk_manager.ts
packages/node-opcua-end2end-test/test/test_issue_1335.ts
packages/node-opcua-secure-channel/source/server/server_secure_channel_layer.ts
packages/node-opcua-server/package.json
packages/node-opcua-server/source/opcua_server.ts
packages/node-opcua-server/source/server_end_point.ts
packages/node-opcua-transport/source/AcknowledgeMessage.ts
packages/node-opcua-transport/source/HelloMessage.ts
packages/node-opcua-transport/source/i_hello_ack_limits.ts
packages/node-opcua-transport/source/index.ts
packages/node-opcua-transport/source/server_tcp_transport.ts
packages/playground/github1335.ts

ClientSecureChannel: fix connection issue hightlighted when server impose a single chunk

---

packages/node-opcua-client-crawler/source/node_crawler.ts

Hi @erossignon, I found this https://github.com/node-opcua/node-opcua/pull/1330, but look like the author does not sign CLA and this PR is not merged yet, I need this feature asap so I create this PR. Thanks

feat: add description and displayName to base object when crawling

---

packages/node-opcua-address-space/src/_mandatory_child_or_requested_optional_filter.ts
packages/node-opcua-address-space/src/base_node_private.ts
packages/node-opcua-address-space/test/test_issue_1320.ts
packages/node-opcua-address-space/test/test_object_instantiate_nested.ts
packages/node-opcua-data-model/source/qualified_name.ts

Bug fix for issue #1320. Depends on PR #1328! Description of problem and solution is discussed in issue.

Fix variable with same name as object type
